database:
  host: "localhost"
  port: 7777
  user: "root"
  password: ""

opening-points: [] # Точки добавляются при использовании определённой команды внутри плагина.
  # example: - world;0.0;0.0;0.0;box-name.yml;effector
  # world - игровой мир, где будет точка открытия.
  # Следующие три координаты - место, где будет точка открытия
  # box-name.yml - название коробки
  # Effector - желаемый эффектор. Можно оставить NONE, если эффектор не нужен

available-commands:
  - ""
  - "&6- /cases select-mode point-open <name>"
  - "&6- /cases editor"
  - ""

system-messages:
  use-console: "&cВы не можете использовать эту команду из консоли."
  error: "&cПроизошла непредвиденная ошибка работы плагина. Посмотрите в консоль."

messages:
  point-create: "&7[&6Cases&7] &aВы успешно создали точку открытия коробки."
  effector-apply: "&7[&6Cases&7] &aВы успешно применили эффектор к этой точке открытия."
  effector-remove: "&7[&6Cases&7] &aВы успешно убрали эффектор у этой точки открытия."
  point-is-open: "&7[&6Cases&7] &cКакой-то игрок уже открывает коробку."